### ISSUE TITLE
Xmind is out of date

### ISSUE THREAD

**Issue by FranklinYu** [dbkblk/chocolatey_packages#2]
Latest version is 3.7.7.

In addition, please update the `packageSourceUrl` field.

**Comment by dbkblk** [comment]
Hi. Thank you for the report.

The github repository of Xmind still show 3.7.5
https://github.com/xmindltd/xmind/releases
Which url is the new packageSourceUrl you talk about?

Unless there is another way to grab this version automatically, the version will stay that way.

**Comment by FranklinYu** [comment]
By `packageSourceUrl` I meant

https://github.com/dbkblk/chocolatey_packages/blob/795a0fc2f08255e18ff3aa7e6385daab14e37361/src/xmind/xmind.nuspec#L22

currently the link gives 404.

**Comment by FranklinYu** [comment]
Even the current version itself is already confusing. According to <https://github.com/xmindltd/xmind/releases/tag/R3.7.5> the build number for 3.7.5 is `R3.7.5.201709290120`, so I expected to see that when I install this Chocolatey package. However, I actually see

> Version: XMind 8 Update 6 (R3.7.6.201711210129)

so “Update 6” seems to be 3.7.6. I’m not familiar with AU or Ketarin so I’m not able to help, but I guess there is some misunderstanding in the updater. I don’t think the current version for “Update 6” is grabbed as expected.
