### ISSUE TITLE
Terminus failure to uninstall

### ISSUE THREAD

**Issue by d1vanloon** [dbkblk/chocolatey_packages#4]
I tried to uninstall Terminus via `choco uninstall terminus`. Chocolatey reported uninstall success, but Terminus was not uninstalled. I ended up using the Windows uninstall tool to remove Terminus.

Chocolatey logs: https://gist.github.com/d1vanloon/5f90a98cb7b173eae708cfa220370de1

**Comment by ghost** [comment]
It seems like it's been fixed.

cinst -y terminus --version 1.0.88
cuninst -y terminus

**Comment by dbkblk** [comment]
Thank you. I'll close the issue if it's fixed :)
