### ISSUE TITLE
Terminus has been outdated for three months.

### ISSUE THREAD

**Issue by ghost** [dbkblk/chocolatey_packages#5]
Would you like some assistance?
If you added me as the maintainers, then I’ll create an AU script for one.

**Comment by dbkblk** [comment]
Sure! I don't have enough time to maintain Terminus. Do you want to own the chocolatey package as well?

**Comment by ghost** [comment]
It's more convenient for me.
I'm not familiar with AppVeyor and Github collaborate.
Please add me(Sanshiro) to the maintainers.

**Comment by dbkblk** [comment]
I have added you as a maintainer on Chocolatey and I'll disable the automatic push here. Obviously, it doesn't work well as the dev is changing things regarding setup quite often.

**Comment by ghost** [comment]
I've submitted one. Thanks.
https://chocolatey.org/packages/terminus/1.0.88
