### ISSUE TITLE
microsoft-r-open 3.5.3 not available via chocolatey

### ISSUE THREAD

**Issue by h-v-r** [dbkblk/chocolatey_packages#6]
Dear Hadrien Dussuel,

First of all, I'm new to this so please excuse me if I raise an obvious issue. When I install microsoft-r-open through Chocolatey, it installs version 3.5.2. I see that your code refers to version 3.5.3, but apparently something goes wrong. Anything I can do?

Best,
Henk

**Comment by dbkblk** [comment]
Hi!

Oh my! Thank you for the report :)
The 3.5.3 package has been generated from the start but wasn't published automatically on Chocolatey!

I'll repush it today!

Hadrien

**Comment by dbkblk** [comment]
Hey! I've fixed that yesterday :) It should be okay once Chocolatey validate it!
