### ISSUE TITLE
FileNotFoundError when running python.exe .\pack.py

### ISSUE THREAD

**Issue by lackovic** [dbkblk/chocolatey_packages#8]
I forked this repo (see [here](https://github.com/lackovic/chocopy)), it was working fine until recently. Now I am getting the following error:
```powershell
python.exe .\pack.py
['bulkrenameutility']
Checking -> bulkrenameutility
Packing -> bulkrenameutility | 4.0.0.3
Chocolatey v2.4.1
Attempting to build package from 'bulkrenameutility.nuspec'.
Successfully created package 'C:\src\chocopy\tmp\bulkrenameutility.4.0.0.3.nupkg'
Traceback (most recent call last):
  File "C:\src\chocopy\pack.py", line 57, in <module>
    os.rename("tmp/" + p + "." + versionLocal + ".nupkg", "packed/" + p + "." + versionLocal + ".nupkg")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'tmp/bulkrenameutility.4.0.0.3 .nupkg' -> 'packed/bulkrenameutility.4.0.0.3 .nupkg'
``` 
Using **Python 3.12.8**. Any idea how to fix it?

**Comment by lackovic** [comment]
The reason of the failure was on [line 22](https://github.com/lackovic/chocopy/blob/514a88da897f9b3f5827b4b67f94c686ac2879b1/pack.py#L22):

```python
versionLocal = versionLocalData["version"]
```

The version contained a trailing space. I fixed it by replacing the line with:

```python
versionLocal = versionLocalData["version"].strip()
```

**Comment by dbkblk** [comment]
Thank you for taking care of this, I merged the commit :)
Do you want to be a member of this repo to make it easier for you in the future?

**Comment by lackovic** [comment]
Sure, I can be a member :)
